mlrNotificationServicePwd: test
mlrEmailTemplateFrom: test@test.test
mlrEmailTemplateText: TemplateTest-
mlrEmailTemplateSubject: test
spring:
  mail:
    host: localhost
    port: 25545
    defaultEncoding: UTF-8
    protocol: smtp