mlrNotificationServicePwd: test
MLR_EMAIL_TEMPLATE_FROM: test@test.test
MLR_EMAIL_TEMPLATE_TEXT: TemplateTest-
spring:
  mail:
    host: localhost
    port: 255
    #username: test
    #password: test
    defaultEncoding: UTF-8
    protocol: smtp
    #tls: true
    #properties.mail.smtp:
    #  auth: true
    #  starttls.enable: true
    #  ssl.trust: <trust url>